### ISSUE TITLE
Средства на балансе не учитываются при пополнении карты на указанную сумму

### ISSUE THREAD

**Issue by Slava-82** [Slava-82/Diplom#1]
# При пополнении карты средства на балансе не суммируются с суммой пополнения

#  https://github.com/Slava-82/Diplom/blob/6461a7c67a83c35b1255bb8e6861be14027aafab/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

# Шаги воспроизведения 
1. Создать объект класса CreditAccount: с начальным балансом: 1000, кредитный лимит: 5000, процентная ставка: 15 
2. Пополнить счёт на 3000 рублей

*Ожидаемый результат:* Баланс будет равен 4000 руб.
*Фактический результат:* Баланс равен 3000 руб. 
# Тест 
https://github.com/Slava-82/Diplom/blob/e67d336fff0f648a88941662835427d98a9fd4e9/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L22

# Окружение  
* **Операционная система:** Windows 10 Pro, Версия	22H2, Сборка ОС	19045.3930
* **IDE:** IntelliJ IDEA 2023.3.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by marinaolivekey** [comment]
fix
balance = balance + amount;
