### ISSUE TITLE
Не проходит оплата, после которой баланс равен минимальному балансу

### ISSUE THREAD

**Issue by marinaolivekey** [Slava-82/Diplom#10]
# Описание
Не проходит оплата, при которой баланс уменьшеается до минимального ровно.

# Локация дефекта
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L46

# Шаги воспроизведения
1) Создать объект SavingAccount класса с начальным балансом: 1_000, минимальным балансом: 0, максимальным балансом: 50_000 р, ставкой: 5. 
2) Сделать покупку на сумму 1_000.

_Ожидаемый результат_ true 
_Фактический результат_ false

# Тест
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L123

# Окружение
Операционная система macOS 13.6.4 (22G513)
IDE IntelliJ IDEA 2021.1.3 (Community Edition)
JAVA OpenJDK 11

**Comment by Slava-82** [comment]
## Исправлено. Соответствует требованиям. 

```
public boolean pay(int amount) {

        if (amount <= 0 || balance - amount < minBalance) {
            return false;
        }
        balance -= amount;
        return true;
    }
```
