### ISSUE TITLE
Баланс не увеличивается при пополнении карты, а приравнивается к сумме пополнения

### ISSUE THREAD

**Issue by marinaolivekey** [Slava-82/Diplom#11]
# Описание
Баланс не увеличивается при пополнении карты, а приравнивается к сумме пополнения

# Локация дефекта
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67

# Шаги воспроизведения
1) Создать объект SavingAccount класса с начальным балансом: 1_000, минимальным балансом: 0, максимальным балансом: 50_000 р, ставкой: 5. 
2) Сделать пополнение на сумму 999.

_Ожидаемый результат_   1_999
_Фактический результат_   999

# Тест
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L186

# Окружение
Операционная система macOS 13.6.4 (22G513)
IDE IntelliJ IDEA 2021.1.3 (Community Edition)
JAVA OpenJDK 11

**Comment by Slava-82** [comment]
## Исправлено. Соответствует требованиям.

```
public boolean add(int amount) {
        if (amount <= 0 || balance + amount > maxBalance) {
            return false;
        } else {
            balance += amount;
            return true;
        }
    }
```
