### ISSUE TITLE
Отсутствует исключение вида IllegalArgumentException, если начальный баланс больше максимального

### ISSUE THREAD

**Issue by marinaolivekey** [Slava-82/Diplom#13]
# Описание
Если начальный баланс больше максимального, должно выходить сообщение об ошибке и не создаваться объект

# Локация дефекта
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
Создать объект SavingAccount класса с начальным балансом: 60_000, минимальным балансом: 1_000, максимальным балансом: 50_000 р, ставкой: 5.

# Ожидаемый результат Сообщение "начальный балас не должен быть больше максимального, а у вас: 60_000"
Фактический результат Сообщение: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Тест
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L68

# Окружение
Операционная система macOS 13.6.4 (22G513)
IDE IntelliJ IDEA 2021.1.3 (Community Edition)
JAVA OpenJDK 11

**Comment by Slava-82** [comment]
## Исправлено. Соответствует требованиям.
```
if (initialBalance > maxBalance) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть больше максимального баланса, а у вас: "
                            + " начальный баланс: " + initialBalance + " больше максимального баланса: " + maxBalance

            );
        }
        this.balance = initialBalance;
        this.minBalance = minBalance;
        this.maxBalance = maxBalance;
        this.rate = rate;
```
