### ISSUE TITLE
Не учитываются средства имеющиеся на балансе при оплате картой

### ISSUE THREAD

**Issue by Slava-82** [Slava-82/Diplom#2]
# При оплате картой средства на балансе не учитываются

#  https://github.com/Slava-82/Diplom/blob/6461a7c67a83c35b1255bb8e6861be14027aafab/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения 
1. Создать объект класса CreditAccount: с начальным балансом: 1000, кредитный лимит: 5000, процентная ставка: 15 
2. Оплатить картой покупку на сумму 3000 рублей

*Ожидаемый результат:* Баланс будет равен -2000 руб.
*Фактический результат:* Баланс равен -3000 руб. 
# Тест 
https://github.com/Slava-82/Diplom/blob/f0d136c3294565efccc61e6a80a65d22cbf07b51/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L63

# Окружение  
* **Операционная система:** Windows 10 Pro, Версия 22H2, Сборка ОС	19045.3930
* **IDE:** IntelliJ IDEA 2023.3.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by marinaolivekey** [comment]
balance = balance - amount;
