### ISSUE TITLE
Проценты начисляются при положительном балансе

### ISSUE THREAD

**Issue by Slava-82** [Slava-82/Diplom#4]
# Описание
При положительном балансе начисляются проценты при вызове метода yearChange

# https://github.com/Slava-82/Diplom/blob/6461a7c67a83c35b1255bb8e6861be14027aafab/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения 
1. Создать объект класса CreditAccount: с начальным балансом: 200, кредитный лимит: 5000, процентная ставка: 15 
2. Вызвать метод  yearChange

*Ожидаемый результат:* Ответ должен быть 0.
*Фактический результат:* Ответ 30. 
# Тест 
https://github.com/Slava-82/Diplom/blob/f0d136c3294565efccc61e6a80a65d22cbf07b51/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L119

# Окружение  
* **Операционная система:** Windows 10 Pro, Версия 22H2, Сборка ОС	19045.3930
* **IDE:** IntelliJ IDEA 2023.3.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by marinaolivekey** [comment]
if (balance >= 0) {
            return 0;
        }
        else {
            return balance / 100 * rate;
            }
        }
