### ISSUE TITLE
Отсутствует исключение вида IllegalArgumentException при отрицательном первоначальном балансе

### ISSUE THREAD

**Issue by Slava-82** [Slava-82/Diplom#6]
# Описание
При отрицательном первоначальном балансе должно выкидываться исключения вида IllegalArgumentException содержащее сообщение "Первоначальный баланс не может быть отрицательным, а у вас: -1000". 

# https://github.com/Slava-82/Diplom/blob/6461a7c67a83c35b1255bb8e6861be14027aafab/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения 
1. Создать объект класса CreditAccount: с начальным балансом: -1000, кредитный лимит: 5000, процентная ставка: 15 
2. Вызвать метод JUnit assertThrows() для проверки исключений.

Ожидаемый результат:Сообщение: "Первоначальный баланс не может быть отрицательным, а у вас: -1000".
Фактический результат: Сообщение: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Тест 
https://github.com/Slava-82/Diplom/blob/f0d136c3294565efccc61e6a80a65d22cbf07b51/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L141

# Окружение  
* **Операционная система:** Windows 10 Pro, Версия 22H2, Сборка ОС	19045.3930
* **IDE:** IntelliJ IDEA 2023.3.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by marinaolivekey** [comment]
if (initialBalance < 0) {

            throw new IllegalArgumentException(
                    "Первоначальный баланс не может быть отрицательным, а у вас: " + initialBalance
            );
        }
