### ISSUE TITLE
Не срабатывает исключение IllegalArgumentException, если ставка отрицательная

### ISSUE THREAD

**Issue by marinaolivekey** [Slava-82/Diplom#7]
# Описание
Если ставка отрицательная, должно выходить сообщение об ошибке и не создаваться объект

# Локация дефекта
https://github.com/Slava-82/Diplom/blob/afef6774b3a47deb2c0bd30f154fa0158b744125/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

# Шаги воспроизведения
Создать объект SavingAccount класса с начальным балансом: 0, минимальным балансом: 0, максимальным балансом: 50_000 р, ставкой: -1.

_Ожидаемый результат_ СообщениеСообщение "Накопительная ставка не может быть отрицательной, а у вас: -1"

_Фактический результат_ Сообщение: java.lang.IllegalArgumentException: Накопительная ставка не может быть отрицательной, а у вас: -1

# Тест
https://github.com/Slava-82/Diplom/blob/a9cc781b832a43116951a4ab357ad3e874413fb1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L42

# Окружение
Операционная система macOS 13.6.4 (22G513)
IDE IntelliJ IDEA 2021.1.3 (Community Edition)
JAVA OpenJDK 11

**Comment by Slava-82** [comment]
# Попробуй таким тестом проверить.
```
@Test
    public void ShouldNotCreateSavingAccountRateMinus1() {
        Assertions.assertThrows(IllegalArgumentException.class,
                () ->{
                    new SavingAccount(0, 0, 50_000, -1);
                });
    }  
```

**Comment by marinaolivekey** [comment]
спасибо!
